server:
  port: 9091

spring:
  application:
    name: eureka-consumer

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix: DEBUG