server:
  port: 9090

spring:
  application:
    name: eureka-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    users:
      path: /users/**
      serviceId: eureka-consumer
